load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bench_common_lib",
    hdrs = [
        "bench_common.h",
        "bench_tracy.h",
        "constants.h",
        "fragment.h",
    ],
    includes = ["."],
    deps = ["@tracy"],
)

_VSOMEIP_COVESA_DEPS = [
    "@vsomeip_covesa//:vsomeip",
    "@vsomeip_covesa//:vsomeip-sd",
    "@vsomeip_covesa//:vsomeip-cfg",
    "@vsomeip_covesa//:vsomeip-e2e",
]

_VSOMEIP_SGMENON_DEPS = [
    "@vsomeip_sgmenon//:vsomeip",
    "@vsomeip_sgmenon//:vsomeip-sd",
    "@vsomeip_sgmenon//:vsomeip-e2e",
]

# buildifier: disable=no-effect
[
    cc_binary(
        name = "event_client_{repo}".format(repo = repo),
        srcs = ["event_client.cc"],
        data = data,
        deps = [":bench_common_lib"] + deps,
    )
    for repo, deps, data in [
        (
            "covesa",
            _VSOMEIP_COVESA_DEPS,
            [
                "@vsomeip_covesa//:vsomeip3-cfg",
                "@vsomeip_covesa//:vsomeip3-sd",
                "@vsomeip_covesa//:vsomeip3-e2e",
            ],
        ),
        (
            "sgmenon",
            _VSOMEIP_SGMENON_DEPS,
            [
                "@vsomeip_sgmenon//:vsomeip3-cfg",
                "@vsomeip_sgmenon//:vsomeip3-sd",
                "@vsomeip_sgmenon//:vsomeip3-e2e",
            ],
        ),
    ]
] + [
    cc_binary(
        name = "event_service_{repo}".format(repo = repo),
        srcs = ["event_service.cc"],
        data = data,
        deps = [":bench_common_lib"] + deps,
    )
    for repo, deps, data in [
        (
            "covesa",
            _VSOMEIP_COVESA_DEPS,
            [
                "@vsomeip_covesa//:vsomeip3-cfg",
                "@vsomeip_covesa//:vsomeip3-sd",
                "@vsomeip_covesa//:vsomeip3-e2e",
            ],
        ),
        (
            "sgmenon",
            _VSOMEIP_SGMENON_DEPS,
            [
                "@vsomeip_sgmenon//:vsomeip3-cfg",
                "@vsomeip_sgmenon//:vsomeip3-sd",
                "@vsomeip_sgmenon//:vsomeip3-e2e",
            ],
        ),
    ]
]
